[package]
name = "test-fixture"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "glob-source",
    "glob-inner",
    "named-source",
    "proc-macro-fixture",
    "renamed-lib-package",
]

[features]
default = ["full"]
full = ["extra"]
extra = []
experimental = []

[dependencies]
glob-source = { path = "glob-source" }
named-source = { path = "named-source" }
